### ISSUE TITLE
Sugestion:  Is there an easy way to add this to the httpx?

### ISSUE THREAD

**Issue by klint-k** [DavidWittman/requests-random-user-agent#17]
Is there an easy way to add this to the httpx?

**Comment by FuckingToasters** [comment]
Yo, i wanted to ask the exact same question. anyone might say us if it works with httpx libary?

**Comment by DavidWittman** [comment]
There is not; the two libraries are different enough that I'd probably just make a separate library if I were to implement support for httpx. I'll look into it though!
